<a href="https://colab.research.google.com/github/R0ckie/Laboratory-8/blob/main/201911167_LinAlg_Lab8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


$$
L = \left\{
    \begin{array}\\
        5yx+5y+5z = 25\\ 
        3x -3y -3z = 21 \\
        15x - 15y + 2z= -35
    \end{array}
\right. $$

$$
\begin{bmatrix}5&5&5\\3&-3&-3\\15&-15&2\end{bmatrix} \cdot \begin{bmatrix}x\\ y\\ z\end{bmatrix} = \begin{bmatrix}25\\21\\-35\end{bmatrix}
$$

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
K = np.array([[5,5,5],
              [3, -3, -3],
              [15, 15, 2]
              ], dtype= float)
L = np.array([
               [25],
               [21],
               [-35]
            ], dtype= float)

K_inv = np.linalg.inv(K)
B = K_inv @ L

print("Matrix K: \n", K ,
      "\n Matrix L: \n" ,L ,
      "\n Answer using inverse: \n " , np.around(B,2)
      )

K_solve = np.around(np.linalg.solve(K,L), 2)

print("Answer using linalg.solve: \n" ,K_solve)

Matrix K: 
 [[ 5.  5.  5.]
 [ 3. -3. -3.]
 [15. 15.  2.]] 
 Matrix L: 
 [[ 25.]
 [ 21.]
 [-35.]] 
 Answer using inverse: 
  [[ 6.  ]
 [-9.46]
 [ 8.46]]
Answer using linalg.solve: 
 [[ 6.  ]
 [-9.46]
 [ 8.46]]
